<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class PostTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('posts')->insert([
        [
            'user_id'                    => '1',
            'admin_id'                   => '1',
            'location_id'                => '1',
            'category_id'                =>  '1',
            'price'                      =>  '10',
            'amount'                     =>  '1',
            'gender'                     => '3',
            'title'                      => 'Trông bé 4 tuổi các ngày 2 4 6 ',
            'start_time'                 => '01-10-2019',
            'end_time'                   => '20-10-2019',
            'rules'                      => '1',
            'status'                     => '1',
            'provider'                   => '0',
            'provider_id'                => '0',
        ],
            [
                'user_id'                    => '3',
                'admin_id'                   => '1',
                'location_id'                => '1',
                'category_id'                =>  '2',
                'price'                      =>  '10',
                'amount'                     =>  '1',
                'gender'                     => '3',
                'title'                      => 'Ship đơn ra đông quan ',
                'start_time'                 => '01-10-2019',
                'end_time'                   => '01-10-2019',
                'rules'                     => '1',
                'status'                   => '1',
                'provider'                 => '0',
                'provider_id'              => '0',
            ],
            [
                'user_id'                    => '1',
                'admin_id'                   => '1',
                'location_id'                => '1',
                'category_id'                =>  '1',
                'price'                      =>  '10',
                'amount'                     =>  '1',
                'gender'                     => '3',
                'title'                      => 'Trông bé 4 tuổi các ngày 2 4 6 ',
                'start_time'                 => '01-10-2019',
                'end_time'                   => '20-10-2019',
                'gender'                   => '3',
                'rules'                    => '1',
                'status'                   => '1',
                'provider'                 => '0',
                'provider_id'              => '0',
            ],
            [
                'user_id'                    => '1',
                'admin_id'                   => '1',
                'location_id'                => '1',
                'category_id'                =>  '1',
                'price'                      =>  '10',
                'amount'                     =>  '1',
                'gender'                     => '3',
                'title'                      => 'Trông bé 4 tuổi các ngày 2 4 6 ',
                'start_time'                 => '01-10-2019',
                'end_time'                   => '20-10-2019',
                'gender'                   => '3',
                'rules'                    => '1',
                'status'                   => '1',
                'provider'                 => '0',
                'provider_id'              => '0',
            ],
            [
                'user_id'                    => '1',
                'admin_id'                   => '1',
                'location_id'                => '1',
                'category_id'                =>  '1',
                'price'                      =>  '10',
                'amount'                     =>  '1',
                'gender'                     => '3',
                'title'                      => 'Trông bé 4 tuổi các ngày 2 4 6 ',
                'start_time'                 => '01-10-2019',
                'end_time'                   => '20-10-2019',
                'gender'                   => '3',
                'rules'                    => '1',
                'status'                   => '1',
                'provider'                 => '0',
                'provider_id'              => '0',
            ],
            [
                'user_id'                    => '1',
                'admin_id'                   => '1',
                'location_id'                => '1',
                'category_id'                =>  '1',
                'price'                      =>  '10',
                'amount'                     =>  '1',
                'gender'                     => '3',
                'title'                      => 'Trông bé 4 tuổi các ngày 2 4 6 ',
                'start_time'                 => '01-10-2019',
                'end_time'                   => '20-10-2019',
                'gender'                   => '3',
                'rules'                    => '1',
                'status'                   => '1',
                'provider'                 => '0',
                'provider_id'              => '0',
            ],
            [
                'user_id'                    => '1',
                'admin_id'                   => '1',
                'location_id'                => '1',
                'category_id'                =>  '1',
                'price'                      =>  '10',
                'amount'                     =>  '1',
                'gender'                     => '3',
                'title'                      => 'Trông bé 4 tuổi các ngày 2 4 6 ',
                'start_time'                 => '01-10-2019',
                'end_time'                   => '20-10-2019',
                'rules'                    => '1',
                'status'                   => '1',
                'provider'                 => '0',
                'provider_id'              => '0',
            ],
            [
                'user_id'                    => '1',
                'admin_id'                   => '1',
                'location_id'                => '1',
                'category_id'                =>  '1',
                'price'                      =>  '10',
                'amount'                     =>  '1',
                'gender'                     => '3',
                'title'                      => 'Trông bé 4 tuổi các ngày 2 4 6 ',
                'start_time'                 => '01-10-2019',
                'end_time'                   => '20-10-2019',
                'rules'                    => '1',
                'status'                   => '1',
                'provider'                 => '0',
                'provider_id'              => '0',
            ],
            [
                'user_id'                    => '1',
                'admin_id'                   => '1',
                'location_id'                => '1',
                'category_id'                =>  '1',
                'price'                      =>  '10',
                'amount'                     =>  '1',
                'gender'                     => '3',
                'title'                      => 'Trông bé 4 tuổi các ngày 2 4 6 ',
                'start_time'                 => '01-10-2019',
                'end_time'                   => '20-10-2019',
                'rules'                    => '1',
                'status'                   => '1',
                'provider'                 => '0',
                'provider_id'              => '0',
            ],
            [
                'user_id'                    => '1',
                'admin_id'                   => '1',
                'location_id'                => '1',
                'category_id'                =>  '1',
                'price'                      =>  '10',
                'amount'                     =>  '1',
                'gender'                     => '3',
                'title'                      => 'Trông bé 4 tuổi các ngày 2 4 6 ',
                'start_time'                 => '01-10-2019',
                'end_time'                   => '20-10-2019',
                'rules'                    => '1',
                'status'                   => '1',
                'provider'                 => '0',
                'provider_id'              => '0',
            ],
            [
                'user_id'                    => '1',
                'admin_id'                   => '1',
                'location_id'                => '1',
                'category_id'                =>  '1',
                'price'                      =>  '10',
                'amount'                     =>  '1',
                'gender'                     => '3',
                'title'                      => 'Trông bé 4 tuổi các ngày 2 4 6 ',
                'start_time'                 => '01-10-2019',
                'end_time'                   => '20-10-2019',
                'rules'                    => '1',
                'status'                   => '1',
                'provider'                 => '0',
                'provider_id'              => '0',
            ],[
                'user_id'                    => '1',
                'admin_id'                   => '1',
                'location_id'                => '1',
                'category_id'                =>  '1',
                'price'                      =>  '10',
                'amount'                     =>  '1',
                'gender'                     => '3',
                'title'                      => 'Trông bé 4 tuổi các ngày 2 4 6 ',
                'start_time'                 => '01-10-2019',
                'end_time'                   => '20-10-2019',
                'rules'                    => '1',
                'status'                   => '1',
                'provider'                 => '0',
                'provider_id'              => '0',
            ],
            [
                'user_id'                    => '1',
                'admin_id'                   => '1',
                'location_id'                => '1',
                'category_id'                =>  '1',
                'price'                      =>  '10',
                'amount'                     =>  '1',
                'gender'                     => '3',
                'title'                      => 'Trông bé 4 tuổi các ngày 2 4 6 ',
                'start_time'                 => '01-10-2019',
                'end_time'                   => '20-10-2019',
                'rules'                    => '1',
                'status'                   => '1',
                'provider'                 => '0',
                'provider_id'              => '0',
            ],
            [
                'user_id'                    => '1',
                'admin_id'                   => '1',
                'location_id'                => '1',
                'category_id'                =>  '1',
                'price'                      =>  '10',
                'amount'                     =>  '1',
                'gender'                     => '3',
                'title'                      => 'Trông bé 4 tuổi các ngày 2 4 6 ',
                'start_time'                 => '01-10-2019',
                'end_time'                   => '20-10-2019',
                'rules'                    => '1',
                'status'                   => '1',
                'provider'                 => '0',
                'provider_id'              => '0',
            ],
            [
                'user_id'                    => '3',
                'admin_id'                   => '1',
                'location_id'                => '1',
                'category_id'                =>  '2',
                'price'                      =>  '10',
                'amount'                     =>  '2',
                'gender'                     => '3',
                'title'                      => 'Ship ra đông quan 2 đơn ',
                'start_time'                 => '01-10-2019',
                'end_time'                   => '01-10-2019',
                'rules'                    => '1',
                'status'                   => '1',
                'provider'                 => '0',
                'provider_id'              => '0',
            ],
            [
                'user_id'                    => '1',
                'admin_id'                   => '1',
                'location_id'                => '1',
                'category_id'                =>  '1',
                'price'                      =>  '10',
                'amount'                     =>  '1',
                'gender'                     => '3',
                'title'                      => 'Trông bé 4 tuổi các ngày 2 4 6 ',
                'start_time'                 => '01-10-2019',
                'end _time'                   => '20-10-2019',
                'gender'                   => '3',
                'rules'                    => '1',
                'status'                   => '1',
                'provider'                 => '0',
                'provider_id'              => '0',
            ],
        ]);
    }
}
