<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class PostTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker    = Faker\Factory::create();

        DB::table('posts')->insert([
            [
                'user_id' => '1',
                'admin_id' => '1',
                'location_id' => '1',
                'category_id' => '2',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Trông bé 4 tuổi các ngày 2 4 6 ',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],
            [
            'user_id' => '3',
            'admin_id' => '1',
            'location_id' => '3',
            'category_id' => '1',
            'price' => '10',
            'amount' => '1',
            'gender' => '1',
            'title' => 'Dọn nhà 2 tầng',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
            'address' => 'số 3 đường Cầu Giấy',
            'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
            'status'       => '1',
            ],
            [
                'user_id' => '4',
                'admin_id' => '1',
                'location_id' => '4',
                'category_id' => '2',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Tưới Cây vào buổi sáng',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Trần Phú',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],
            [
                'user_id' => '3',
                'admin_id' => '1',
                'location_id' => '6',
                'category_id' => '1',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => ' tuyển nhân viên tư vấn ',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],
            [
                'user_id' => '4',
                'admin_id' => '1',
                'location_id' => '4',
                'category_id' => '1',
                'price' => '10',
                'amount' => '2',
                'gender' => '1',
                'title' => 'Giúp việc dọn nhà cửa ',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],
            [
                'user_id' => '4',
                'admin_id' => '1',
                'location_id' => '4',
                'category_id' => '4',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Trông bé 4 tuổi các ngày 3 5 ',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],
            [
                'user_id' => '3',
                'admin_id' => '1',
                'location_id' => '3',
                'category_id' => '3',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Làm thời vụ ',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],
            [
                'user_id' => '4',
                'admin_id' => '1',
                'location_id' => '7',
                'category_id' => '2',
                'price' => '20',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Làm thời vụ tại Canifa',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],
            [
                'user_id' => '3',
                'admin_id' => '1',
                'location_id' => '1',
                'category_id' => '2',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Sử lap tại nhà',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],
            [
                'user_id' => '4',
                'admin_id' => '1',
                'location_id' => '2',
                'category_id' => '2',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Sửa đường ống nước',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],
            [
                'user_id' => '3',
                'admin_id' => '1',
                'location_id' => '1',
                'category_id' => '2',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Ship đồ sang hà đông ',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],
            [
                'user_id' => '3',
                'admin_id' => '1',
                'location_id' => '1',
                'category_id' => '2',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Đứa bé đi học ',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],
            [
                'user_id' => '3',
                'admin_id' => '1',
                'location_id' => '1',
                'category_id' => '2',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Chăm sóc người già ',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],
            [
                'user_id' => '3',
                'admin_id' => '1',
                'location_id' => '1',
                'category_id' => '2',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Giúp việc nhà ',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],
            [
                'user_id' => '3',
                'admin_id' => '1',
                'location_id' => '1',
                'category_id' => '2',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Phụ giúp trông trẻ',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],[
                'user_id' => '3',
                'admin_id' => '1',
                'location_id' => '1',
                'category_id' => '2',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Đi đón bé về nhà ',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],[
                'user_id' => '3',
                'admin_id' => '1',
                'location_id' => '1',
                'category_id' => '2',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Trông bé vào buổi sáng',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],[
                'user_id' => '3',
                'admin_id' => '1',
                'location_id' => '1',
                'category_id' => '2',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Làm thời vụ tại quán cà phê ',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],[
                'user_id' => '3',
                'admin_id' => '1',
                'location_id' => '1',
                'category_id' => '2',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Làm thời vụ gấp quàn áo',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],[
                'user_id' => '3',
                'admin_id' => '1',
                'location_id' => '1',
                'category_id' => '2',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Sửa điện',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],[
                'user_id' => '3',
                'admin_id' => '1',
                'location_id' => '1',
                'category_id' => '2',
                'price' => '10',
                'amount' => '1',
                'gender' => '1',
                'title' => 'Dọn nhà cửa',
                'start_time' => $faker->dateTime($max = 'now', $timezone = null),
                'end_time' => $faker->dateTime($max = 'now', $timezone = null),
                'address' => 'số 3 đường Cầu Giấy',
                'detail' => '• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.• Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.
                           • Hình thức làm việc: Nhân viên chính thức, Cộng tác viên.',
                'status'       => '1',
            ],
        ]);
    }
}
